[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：不支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Game/GameDownload/GameDownload.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🤖 微软必应,https://raw.githubusercontent.com/warcns/OP/main/Ruleset/Bing.list
;ruleset=🤖 微软必应,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MicrosoftEdge/MicrosoftEdge.list
ruleset=💻 Claude,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
ruleset=🖱️ Gemini,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=💼 领英服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LinkedIn/LinkedIn.list
ruleset=🍏 苹果电视,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🖥️ OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
;ruleset=🕹 PS5认证,https://raw.githubusercontent.com/warcns/OP/main/Ruleset/PS5.list
ruleset=🕹 SONY PS,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/warcns/OP/main/Ruleset/Epic.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
;ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌏 出海媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=🌏 出海媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/IqiyiHMT.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位
;
;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🌥 泡芙节点`[]🔯 故障转移`[]🇸🇬 故障转移狮城`[]🔮 负载均衡`[]⭐️ 收藏节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`HK(0[2-9]|[1-9]\d)`香港 IEPL`Hong Kong`(v3.?.香港)`香港・([1-9]\d)`(IPLC.*香港)`(V3.HKG)`(v1.?.香港)`香港・`(V2.HKG)`(V1.HKG)`(香港.*.X1)`(HK.*.x1)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`香港 IEPL.......P`香港 IEPL.......S`香港 IEPL`Hong Kong`(v3.?.香港)`(IPLC.*香港)`(V3.HKG)`(v1.?.香港)`(V2.HKG)`(V1.HKG)`(香港.*.X1)`(HK.*.x1)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择1`url-test`(v3.?.香港|IPLC.*香港)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`(香港 IEPL.....$)`香港 IEPL`香港 Aliyun`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`(香港 IEPL|香港 Lite|香港 Aliyun)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`!!GROUPID=0!!(香港 IEPL|香港 Lite|香港 Aliyun)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`!!GROUPID=0!!(hk|港)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`(香港 BGP|IEPL)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`(港|HK|Hong Kong|澳门|CTM)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`url-test`(港|HK|Hong Kong|澳门)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=♻️ 自动选择`select`(港|HK|Hong Kong|澳门|CTM)
;custom_proxy_group=🌥 自动选择 泡芙`url-test`(香港IEPL)`http://www.gstatic.com/generate_204`300
custom_proxy_group=🌥 泡芙节点`select`[]🌥 自动选择 泡芙`[]🎲 自动选择 泡芙V1`[]🇸🇬 自动选择 泡芙SG`[]🍭 手动选择 泡芙`[]🔯 故障转移 泡芙
custom_proxy_group=🌥 自动选择 泡芙`url-test`(v3.?.香港)`香港・([1-9]\d)`http://www.gstatic.com/generate_204`300,5,30
custom_proxy_group=🎲 自动选择 泡芙V1`url-test`(v1.?.香港)`香港・`http://www.gstatic.com/generate_204`300,5,30
custom_proxy_group=🇸🇬 自动选择 泡芙SG`url-test`(v3.?.新加坡)`新加坡・(0[6-9]|[1-9]\d)`(v1.?.新加坡)`新加坡・`(IPLC.*新加坡)`(V3.SGP)`(V2.SGP)`(V1.SGP)`(新加坡.*.X1)`(SG.*.x1)`http://www.gstatic.com/generate_204`300,5,30
custom_proxy_group=🍭 手动选择 泡芙`select`(・)
custom_proxy_group=🔯 故障转移 泡芙`fallback`(v3.?.香港)`香港・([1-9]\d)`(V3.HKG)`(V2.HKG)`(V1.HKG)`HK\-A`香港｜Hong`香港 IEPL`HK(0[2-9]|[1-9]\d)`Hong Kong`(v1.?.香港)`香港・`(香港.*.X1)`(HK.*.x1)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🎲 负载均衡 泡芙`load-balance`!!GROUPID=2!!(^(?!.*(v1|香港)).*)`http://www.gstatic.com/generate_204`300
custom_proxy_group=🔯 故障转移`fallback`香港 IEPL`HK(0[2-9]|[1-9]\d)`(?<!｜)Hong Kong`(v3.?.香港)`香港・([1-9]\d)`(V3.HKG)`(v1.?.香港)`香港・`(V2.HKG)`(V1.HKG)`HK\-A`香港｜Hong`(香港.*.X1)`(HK.*.x1)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🔯 故障转移`fallback`香港 IEPL.......S`香港 IEPL`香港 OCTO`(v3.?.香港)`香港 Aliyun`香港 DMIT`香港 BGP`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🔯 故障转移`fallback`IEPL`香港 BGP`!!GROUPID=1!!(v3 香港)`http://www.gstatic.com/generate_204`300⭐️
custom_proxy_group=🇸🇬 故障转移狮城`fallback`新加坡 IEPL`SG(0[2-9]|[1-9]\d)`(?<!｜)Singapore`新加坡・(0[6-9]|[1-9]\d)`新加坡・`(v3.?.新加坡)`(v1.?.新加坡)`(IPLC.*新加坡)`(V3.SGP)`(V2.SGP)`(V1.SGP)`SG\-A`新加坡｜Singapore`(新加坡.*.X1)`(SG.*.x1)`http://www.gstatic.com/generate_204`300,5,30
custom_proxy_group=🔮 负载均衡`load-balance`HK(0[2-9]|[1-9]\d)`Hong Kong`(v3.?.香港)`香港・([1-9]\d)`(V3.HKG)`(v1.?.香港)`香港・`(V2.HKG)`(V1.HKG)`(香港.*.X1)`(HK.*.x1)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🔮 负载均衡`load-balance`(香港 IEPL|香港 AIA)`http://www.gstatic.com/generate_204`300
custom_proxy_group=⭐️ 收藏节点`select`香港 IEPL`香港IEPL`香港 Lite`HK`Hong Kong`台湾 AIA`台湾 IEPL`台湾IEPL`新加坡 Aliyun`新加坡 IEPL`新加坡IEPL`(v3.?.(香港|新加坡|台湾))`IPLC`日本 AIA`日本 IEPL`韩国 AIA`韩国 IEPL`美国 AIA`美国 IEPL`英国 AIA`英国 IEPL`德国 AIA`德国 IEPL`IEPL`Hong Kong`HK`Singapore`SG`Taiwan`TW
;custom_proxy_group=🔮 负载均衡`load-balance`(香港 IEPL|香港 AIA)`http://www.gstatic.com/generate_204`300
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|Hong Kong|澳门)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇨🇳 台湾节点`select`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇰🇷 韩国节点`select`(KR|Korea|KOR|首尔|韩|韓)
custom_proxy_group=🎥 奈飞节点`select`(新加坡|香港|台湾) IEPL`(新加坡|香港|台湾) OCTO`IEPL`OCTO`v3`HK`Hong Kong`香港`SG`Singapore`新加坡`TW`Taiwan`台湾
;custom_proxy_group=🎥 奈飞节点`select`IEPL`AIA`Aliyun`GIA`Lite`v3
custom_proxy_group=🎮 游戏节点`select`Gamer
;custom_proxy_group=🎥 奈飞节点`select`IEPL`台湾`新加坡
;custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media|IEPL|BGP)
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🌥 泡芙节点`[]🔯 故障转移`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🚀 节点选择`[]♻️ 自动选择`[]🌥 泡芙节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🔯 故障转移`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 节点选择`[]⭐️ 收藏节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]DIRECT`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=🌏 出海媒体`select`[]DIRECT`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]⭐️ 收藏节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=💼 领英服务`select`[]DIRECT`[]🚀 节点选择`[]⭐️ 收藏节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🌥 泡芙节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🤖 微软必应`select`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🍏 苹果电视`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🖥️ OpenAI`select`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=💻 Claude`select`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🖱️ Gemini`select`[]🚀 节点选择`[]🌥 泡芙节点`[]⭐️ 收藏节点`[]🇸🇬 狮城节点`[]🇸🇬 故障转移狮城`[]🇸🇬 自动选择 泡芙SG`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
;custom_proxy_group=🕹 PS5认证`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]⭐️ 收藏节点`[]🎮 游戏节点`[]🇭🇰 香港节点`[]🚀 手动切换
custom_proxy_group=🕹 SONY PS`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]⭐️ 收藏节点`[]🎮 游戏节点`[]🌥 泡芙节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]⭐️ 收藏节点`[]🎮 游戏节点`[]🌥 泡芙节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]⭐️ 收藏节点`[]🌥 泡芙节点
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]⭐️ 收藏节点`[]🌥 泡芙节点
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]🌥 泡芙节点`[]🔯 故障转移`[]⭐️ 收藏节点`[]🎮 游戏节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
